apiVersion: v1
kind: Pod
metadata:
  name: postgresql-pod
  labels:
    app: postgresql
spec:
  containers:
  - name: postgresql
    image: postgres:15
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_DB
      value: "myapp"
    - name: POSTGRES_USER
      value: "admin"
    - name: POSTGRES_PASSWORD
      value: "password"
    volumeMounts:
    - name: postgresql-storage
      mountPath: /var/lib/postgresql/data
  volumes:
  - name: postgresql-storage
    emptyDir: {} 