apiVersion: v1
kind: Pod
metadata:
  name: postgresql-pod
  labels:
    app: postgresql
spec:
  containers:
  - name: postgresql
    image: postgres:15
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_DB
      value: "myapp"n
    - name: POSTGRES_USER
      value: "admin"
    - name: POSTGRES_PASSWORD
      value: "password"
    volumeMounts:
    - name: postgresql-storage
      mountPath: /var/lib/postgresql/data
  volumes:
  - name: postgresql-storage
    emptyDir: {} 
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  labels:
    app: postgresql
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP 